(function() {
  function textContent(el) {
    return el ? String(el.textContent || '').trim() : '';
  }

  function normalizeText(value) {
    return value == null ? '' : String(value).trim();
  }

  function toArray(value) {
    if (Array.isArray(value)) return value;
    return value == null ? [] : [value];
  }

  function uniqueNonEmpty(list) {
    var seen = Object.create(null);
    var out = [];
    for (var i = 0; i < list.length; i += 1) {
      var val = normalizeText(list[i]);
      if (!val) continue;
      if (seen[val]) continue;
      seen[val] = true;
      out.push(val);
    }
    return out;
  }

  function queryFirstText(selectors) {
    for (var i = 0; i < selectors.length; i += 1) {
      var node = document.querySelector(selectors[i]);
      var value = textContent(node);
      if (value) return value;
    }
    return '';
  }

  function isAmazonHost() {
    return /(^|\.)amazon\./i.test(location.hostname || '');
  }

  function queryMeta(keys) {
    for (var i = 0; i < keys.length; i += 1) {
      var key = keys[i];
      var selectors = [
        'meta[property="' + key + '"]',
        'meta[name="' + key + '"]'
      ];
      for (var j = 0; j < selectors.length; j += 1) {
        var node = document.querySelector(selectors[j]);
        var value = node ? node.getAttribute('content') : '';
        if (value && String(value).trim()) return String(value).trim();
      }
    }
    return '';
  }

  function parseJsonLdBlocks() {
    var scripts = Array.prototype.slice.call(
      document.querySelectorAll('script[type="application/ld+json"]')
    );
    var docs = [];

    scripts.forEach(function(script) {
      var raw = textContent(script);
      if (!raw) return;
      try {
        var parsed = JSON.parse(raw);
        docs.push(parsed);
      } catch (err) {
        // Ignore invalid JSON-LD blocks generated by some storefronts.
      }
    });
    return docs;
  }

  function collectSchemaNodes(docs) {
    var queue = docs.slice();
    var nodes = [];

    while (queue.length) {
      var current = queue.shift();
      if (!current) continue;
      if (Array.isArray(current)) {
        queue = queue.concat(current);
        continue;
      }
      if (typeof current !== 'object') continue;

      nodes.push(current);
      if (Array.isArray(current['@graph'])) queue = queue.concat(current['@graph']);
      if (Array.isArray(current.mainEntity)) queue = queue.concat(current.mainEntity);
      if (current.mainEntity && typeof current.mainEntity === 'object') queue.push(current.mainEntity);
    }
    return nodes;
  }

  function nodeHasType(node, expectedType) {
    if (!node || !node['@type']) return false;
    var types = toArray(node['@type']).map(function(t) { return String(t).toLowerCase(); });
    return types.indexOf(String(expectedType).toLowerCase()) >= 0;
  }

  function pickFirstUrl(value) {
    var list = toArray(value);
    for (var i = 0; i < list.length; i += 1) {
      var item = list[i];
      if (typeof item === 'string' && /^https?:\/\//i.test(item)) return item;
      if (item && typeof item === 'object') {
        if (typeof item.url === 'string' && /^https?:\/\//i.test(item.url)) return item.url;
        if (typeof item.contentUrl === 'string' && /^https?:\/\//i.test(item.contentUrl)) return item.contentUrl;
      }
    }
    return '';
  }

  function parseSchema(nodes) {
    var product = null;
    var article = null;
    var breadcrumbList = null;

    for (var i = 0; i < nodes.length; i += 1) {
      var node = nodes[i];
      if (!product && nodeHasType(node, 'Product')) product = node;
      if (!article && (nodeHasType(node, 'Article') || nodeHasType(node, 'NewsArticle') || nodeHasType(node, 'BlogPosting'))) {
        article = node;
      }
      if (!breadcrumbList && nodeHasType(node, 'BreadcrumbList')) breadcrumbList = node;
    }

    var breadcrumb = '';
    if (breadcrumbList && Array.isArray(breadcrumbList.itemListElement)) {
      var crumbs = breadcrumbList.itemListElement
        .map(function(item) {
          if (!item || typeof item !== 'object') return '';
          if (typeof item.name === 'string') return item.name;
          if (item.item && typeof item.item === 'object' && typeof item.item.name === 'string') return item.item.name;
          return '';
        })
        .filter(Boolean);
      if (crumbs.length) breadcrumb = crumbs.join(' > ');
    }

    var schema = {};
    if (product) {
      schema.name = normalizeText(product.name);
      schema.brand = normalizeText(
        typeof product.brand === 'string'
          ? product.brand
          : (product.brand && product.brand.name) || ''
      );
      schema.category = normalizeText(product.category);
      schema.color = normalizeText(product.color);
      schema.image = pickFirstUrl(product.image);
      schema.type = 'Product';

      var offers = Array.isArray(product.offers) ? product.offers[0] : product.offers;
      if (offers && typeof offers === 'object') {
        schema.price = extractPriceNumber(offers.price);
      }
    }

    if (!schema.name && article) schema.name = normalizeText(article.headline || article.name);
    if (!schema.image && article) schema.image = pickFirstUrl(article.image);
    if (!schema.purchase_date && article) schema.purchase_date = normalizeText(article.datePublished);
    if (!schema.type && article) schema.type = 'Article';

    if (breadcrumb) schema.breadcrumb = breadcrumb;
    return schema;
  }

  function cleanAmazonBrand(text) {
    var v = normalizeText(text);
    if (!v) return '';
    v = v.replace(/^ブランド[:：]\s*/i, '');
    v = v.replace(/^Visit the\s+(.+?)\s+Store$/i, '$1');
    v = v.replace(/^Brand[:：]\s*/i, '');
    return v.trim();
  }

  function findAmazonName() {
    return queryFirstText([
      '#productTitle',
      '#title',
      '[data-cy="title-recipe"]',
      'h1.a-size-large',
      'h1'
    ]);
  }

  function findAmazonBrand() {
    var fromDom = queryFirstText([
      '#bylineInfo',
      '#brand',
      'a#bylineInfo'
    ]);
    return cleanAmazonBrand(fromDom);
  }

  function findAmazonPrice() {
    var fromText = queryFirstText([
      '#corePrice_feature_div .a-offscreen',
      '#corePriceDisplay_desktop_feature_div .a-offscreen',
      '#corePriceDisplay_desktop_feature_div .reinventPricePriceToPayMargin .a-offscreen',
      '.apexPriceToPay .a-offscreen',
      '.a-price.aok-align-center .a-offscreen'
    ]);
    return extractPriceNumber(fromText);
  }

  function findAmazonImageUrl() {
    var img = document.querySelector('#landingImage');
    if (img && (img.currentSrc || img.src)) return img.currentSrc || img.src;
    var fromWrapper = document.querySelector('#imgTagWrapperId img');
    if (fromWrapper && (fromWrapper.currentSrc || fromWrapper.src)) return fromWrapper.currentSrc || fromWrapper.src;
    return '';
  }

  function findAmazonCategory() {
    var breadcrumb = Array.prototype.slice.call(
      document.querySelectorAll('#wayfinding-breadcrumbs_feature_div li span a, #wayfinding-breadcrumbs_container li span a')
    )
      .map(function(n) { return textContent(n); })
      .filter(Boolean);
    if (breadcrumb.length) return breadcrumb.join(' > ');
    return '';
  }

  function findAmazonRawText() {
    var bullets = Array.prototype.slice.call(
      document.querySelectorAll('#feature-bullets li span.a-list-item, #productFactsDesktop_feature_div li')
    )
      .map(function(n) { return textContent(n); })
      .filter(Boolean);
    if (bullets.length) return bullets.slice(0, 6).join(' / ').slice(0, 400);
    return '';
  }

  function findName() {
    var fromMeta = queryMeta(['og:title', 'twitter:title']);
    if (fromMeta) return fromMeta;

    var h1 = document.querySelector('h1');
    if (h1 && textContent(h1)) return textContent(h1);

    var title = document.title ? String(document.title).trim() : '';
    if (title) return title;

    return '';
  }

  function findImageUrl() {
    var fromMeta = queryMeta(['og:image', 'twitter:image', 'product:image']);
    if (fromMeta) return fromMeta;

    var imgs = Array.prototype.slice.call(document.querySelectorAll('img[src]'));
    var best = imgs
      .map(function(img) {
        var src = img.currentSrc || img.src || '';
        var area = (img.naturalWidth || 0) * (img.naturalHeight || 0);
        return { src: src, area: area };
      })
      .filter(function(item) { return !!item.src; })
      .sort(function(a, b) { return b.area - a.area; });

    return best.length ? best[0].src : '';
  }

  function findBrand() {
    var fromMeta = queryMeta(['product:brand', 'brand', 'og:brand']);
    if (fromMeta) return fromMeta;

    var candidates = [
      '[itemprop="brand"]',
      '.brand',
      '.product-brand',
      '[class*="brand"]'
    ];

    for (var i = 0; i < candidates.length; i += 1) {
      var node = document.querySelector(candidates[i]);
      var value = textContent(node);
      if (value) return value;
    }

    return '';
  }

  function extractPriceNumber(text) {
    if (!text) return '';
    var cleaned = String(text).replace(/[,\s]/g, '');
    var match = cleaned.match(/(?:¥|￥|\$|USD|JPY)?([0-9]+(?:\.[0-9]{1,2})?)/i);
    if (!match) return '';
    var n = Number(match[1]);
    return Number.isFinite(n) ? String(Math.round(n)) : '';
  }

  function pickLikelyPriceText() {
    var selectors = [
      '[itemprop="price"]',
      '[data-price]',
      '[class*="price"]',
      '[id*="price"]'
    ];
    var best = '';
    var bestScore = -1;

    for (var i = 0; i < selectors.length; i += 1) {
      var nodes = Array.prototype.slice.call(document.querySelectorAll(selectors[i]));
      for (var j = 0; j < nodes.length; j += 1) {
        var txt = textContent(nodes[j]);
        if (!txt) continue;
        var score = 0;
        if (/[¥￥$]/.test(txt)) score += 2;
        if (/price|価格|税込|sale|セール/i.test(txt)) score += 2;
        if (/[0-9]/.test(txt)) score += 1;
        if (txt.length > 60) score -= 2;
        if (score > bestScore) {
          best = txt;
          bestScore = score;
        }
      }
    }
    return best;
  }

  function findPrice() {
    var metaPrice = queryMeta([
      'product:price:amount',
      'product:price',
      'og:price:amount',
      'twitter:data1',
      'price'
    ]);
    var parsedMeta = extractPriceNumber(metaPrice);
    if (parsedMeta) return parsedMeta;

    var fromCandidates = extractPriceNumber(pickLikelyPriceText());
    if (fromCandidates) return fromCandidates;

    var bodyText = String(document.body ? document.body.innerText : '');
    var fromBody = extractPriceNumber(bodyText.slice(0, 4000));
    return fromBody || '';
  }

  function findCategory() {
    var fromMeta = queryMeta(['product:category', 'category', 'article:section']);
    if (fromMeta) return fromMeta;

    var breadcrumb = document.querySelector('[aria-label*="breadcrumb" i], .breadcrumb, nav.breadcrumb');
    if (breadcrumb) {
      var txt = textContent(breadcrumb);
      if (txt) return txt.slice(0, 120);
    }
    return '';
  }

  function normalizeDate(value) {
    var v = normalizeText(value);
    if (!v) return '';
    var d = new Date(v);
    if (Number.isNaN(d.getTime())) return '';
    var y = String(d.getFullYear());
    var m = String(d.getMonth() + 1).padStart(2, '0');
    var day = String(d.getDate()).padStart(2, '0');
    return y + '-' + m + '-' + day;
  }

  function findRawText() {
    var desc = queryMeta(['description', 'og:description', 'twitter:description']);
    if (desc) return desc;
    var bodyText = normalizeText(document.body ? document.body.innerText : '');
    return bodyText.slice(0, 400);
  }

  function buildPayload() {
    var schemaDocs = parseJsonLdBlocks();
    var schemaNodes = collectSchemaNodes(schemaDocs);
    var schema = parseSchema(schemaNodes);
    var isAmazon = isAmazonHost();
    var amazonName = isAmazon ? findAmazonName() : '';
    var amazonBrand = isAmazon ? findAmazonBrand() : '';
    var amazonPrice = isAmazon ? findAmazonPrice() : '';
    var amazonImageUrl = isAmazon ? findAmazonImageUrl() : '';
    var amazonCategory = isAmazon ? findAmazonCategory() : '';
    var amazonRawText = isAmazon ? findAmazonRawText() : '';

    var name = uniqueNonEmpty([amazonName, queryMeta(['og:title', 'twitter:title']), schema.name, findName()])[0] || '';
    var brand = uniqueNonEmpty([amazonBrand, queryMeta(['product:brand', 'brand', 'og:brand']), schema.brand, findBrand()])[0] || '';
    var type = uniqueNonEmpty([schema.type])[0] || '';
    var category = uniqueNonEmpty([amazonCategory, queryMeta(['product:category', 'category', 'article:section']), schema.category, schema.breadcrumb, findCategory()])[0] || '';
    var color = uniqueNonEmpty([schema.color])[0] || '';
    var purchaseDate = normalizeDate(uniqueNonEmpty([schema.purchase_date, queryMeta(['article:published_time', 'date'])])[0] || '');
    var price = uniqueNonEmpty([amazonPrice, schema.price, findPrice()])[0] || '';
    var imageUrl = uniqueNonEmpty([amazonImageUrl, queryMeta(['og:image', 'twitter:image', 'product:image']), schema.image, findImageUrl()])[0] || '';
    var rawText = uniqueNonEmpty([amazonRawText, findRawText()])[0] || '';

    return {
      site: location.hostname,
      url: location.href,
      name: name,
      brand: brand,
      type: type,
      category: category,
      category2: '',
      color: color,
      purchase_date: purchaseDate,
      price: price,
      image_url: imageUrl,
      memo: '',
      raw_text: rawText
    };
  }

  // popup.js から executeScript 経由で直接呼べるように公開する。
  if (typeof window !== 'undefined') {
    window.__MONODATA_EXTRACT_PRODUCT__ = buildPayload;
  }

  chrome.runtime.onMessage.addListener(function(message, sender, sendResponse) {
    if (!message || message.type !== 'extractProduct') return;
    try {
      sendResponse({ ok: true, data: buildPayload() });
    } catch (err) {
      sendResponse({ ok: false, error: String(err) });
    }
  });
})();
